[package]
name = "trading-bot"
version = "0.1.0"
authors = ["George Boulougaris <gboulougaris@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
trading-lib = { path = "../lib" }
tungstenite = "0.11.1"
url = "2.1.1"
reqwest = { version = "0.10", features = ["blocking", "json"] }
serde = {version = "1.0.57", features = ["derive"] }
serde_json = "1.0.57"
http = "0.2.1"
native-tls = "0.2.4"
anyhow = "1.0.32"
tch = "0.2.1"
rand = "0.7.3"
chrono = "0.4.19"
clap = "2.33.3"
structopt = "0.3.19"
tempfile = "3.1.0"
plotters = "0.3.0"
